"""Interactive Q&A for Source2Launch's promotion agent.

After initial source analysis, identifies the most critical missing information
and asks the user targeted questions (max 3) to fill in the gaps.
Works for any subject: repos, restaurants, products, events, papers, etc.
"""
from __future__ import annotations

import copy
import re
import sys
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Gap definitions: what's important for good promotional content
# ---------------------------------------------------------------------------

_AI_QUESTION_PROMPT = """\
你是推广内容顾问，正在帮用户生成推广内容。

当前已有信息：
{evidence_brief}

请分析上面的信息，找出最影响推广质量的缺口，生成 {max_q} 个最关键的补充问题。

要求：
- 每行一个问题，直接写问题内容
- 问题要具体，针对这个具体的推广场景
- 不要问已经有答案的信息
- 括号里可以给出回答示例
- 只输出问题，不要编号、解释或其他内容
"""


# ---------------------------------------------------------------------------
# Gap identification
# ---------------------------------------------------------------------------

def identify_gaps(result: dict[str, Any]) -> list[str]:
    """Lightweight structural check — returns gap keys for critical missing info.

    Used only to decide whether to trigger interactive mode.
    Actual questions are generated by AI in ask_and_merge().
    """
    project = result.get("project", {})
    evidence = result.get("evidence", {})
    ctx = evidence.get("additionalContext", {})
    gaps: list[str] = []

    desc = (
        project.get("description") or evidence.get("opening") or evidence.get("readmeOpening") or ""
    )
    if len(str(desc).strip()) < 40:
        gaps.append("description")

    has_cta = (
        project.get("cta") or project.get("installCommand")
        or project.get("homepage") or project.get("repositoryUrl")
        or evidence.get("keyActions") or evidence.get("installCommands")
    )
    if not has_cta:
        gaps.append("cta")

    has_audience = project.get("topics") or ctx.get("audience")
    if not has_audience:
        gaps.append("audience")

    return gaps[:3]


def has_significant_gaps(result: dict[str, Any]) -> bool:
    """Return True if the result is missing critical info to warrant Q&A."""
    gaps = identify_gaps(result)
    return bool({"description", "cta"} & set(gaps)) or len(gaps) >= 2


def _generate_questions_via_ai(
    result: dict[str, Any],
    max_q: int,
    ai_options: dict[str, Any] | None = None,
    env: dict[str, str] | None = None,
) -> list[str]:
    """Ask the AI to generate the most relevant clarifying questions."""
    from .ai import ai_config, post_json, extract_chat_content
    from .promo_prompts import build_evidence_brief
    from .ai import build_promo_payload

    env = env or os.environ
    config = ai_config(ai_options or {}, env)
    if not config.get("apiKey"):
        return []

    payload = build_promo_payload(result)
    brief = build_evidence_brief(payload)

    prompt = _AI_QUESTION_PROMPT.format(evidence_brief=brief, max_q=max_q)
    try:
        resp = post_json(
            f"{config['baseUrl']}/chat/completions",
            {
                "model": config["model"],
                "messages": [{"role": "user", "content": prompt}],
                "max_tokens": 300,
                "temperature": 0.4,
            },
            headers={"Authorization": f"Bearer {config['apiKey']}"},
            timeout=15,
        )
        raw = extract_chat_content(resp).strip()
        questions = [q.strip() for q in raw.splitlines() if q.strip()]
        return questions[:max_q]
    except Exception:  # noqa: BLE001
        return []


# ---------------------------------------------------------------------------
# Interactive Q&A
# ---------------------------------------------------------------------------

def ask_and_merge(
    result: dict[str, Any],
    *,
    force: bool = False,
    max_questions: int = 3,
    ai_options: dict[str, Any] | None = None,
    env: dict[str, str] | None = None,
) -> dict[str, Any]:
    """Ask the user up to max_questions AI-generated clarifying questions.

    Questions are generated by the AI based on what information is missing —
    no hardcoded question templates.
    Silently skips in non-TTY contexts.
    """
    if not sys.stdin.isatty():
        return result

    gaps = identify_gaps(result)
    if not force and not gaps:
        return result

    project_name = result.get("project", {}).get("name") or "你的推广主体"
    print(f"\n✦ 已分析「{project_name}」，AI 正在判断还需要哪些信息…", file=sys.stderr)

    # Let AI generate the questions
    questions = _generate_questions_via_ai(result, max_questions, ai_options, env)

    if not questions:
        # Fallback: generic prompt if AI is unavailable
        questions = ["还有什么补充信息可以提供吗？（地址、图片、受众、价格等）"]

    print(f"\n  补充以下信息可以让推广内容更好（直接回车跳过）：\n", file=sys.stderr)

    answers: list[tuple[str, str]] = []  # (question, answer)
    for i, question in enumerate(questions, 1):
        print(f"  {i}. {question}", file=sys.stderr)
        try:
            ans = input("     > ").strip()
        except (EOFError, KeyboardInterrupt):
            print("\n（跳过补充，继续生成…）", file=sys.stderr)
            break
        if ans:
            answers.append((question, ans))
        print(file=sys.stderr)

    if not answers:
        return result

    merged = _merge_freeform_answers(result, answers)
    print("✓ 信息补充完成，正在生成推广内容…\n", file=sys.stderr)
    return merged


# ---------------------------------------------------------------------------
# Answer merging
# ---------------------------------------------------------------------------

def _merge_freeform_answers(result: dict[str, Any], answers: list[tuple[str, str]]) -> dict[str, Any]:
    """Merge free-form Q&A pairs into the result dict.

    Automatically handles URLs, file paths, and plain text answers.
    All answers are also stored in additionalContext for the AI to use.
    """
    merged = copy.deepcopy(result)
    project = merged.setdefault("project", {})
    evidence = merged.setdefault("evidence", {})
    ctx = evidence.setdefault("additionalContext", {})

    for question, answer in answers:
        answer = answer.strip()
        if not answer:
            continue

        # Auto-detect answer type and route to the right field
        for part in answer.split():
            part = part.strip()
            if part.startswith(("http://", "https://")):
                # Could be a website or image URL
                if re.search(r"\.(png|jpg|jpeg|gif|webp|svg)(\?|$)", part, re.I):
                    evidence.setdefault("visualUrls", []).append(part)
                else:
                    project["homepage"] = project.get("homepage") or part
            elif Path(part).exists() and Path(part).is_file():
                evidence.setdefault("visuals", []).append(f"![image]({part})")

        # Detect install commands
        if re.match(r"^(npm|pip|pipx|cargo|go install|docker|brew|apt|curl|source2launch)\b", answer, re.I):
            project["cta"] = answer
            project["installCommand"] = answer
            evidence.setdefault("keyActions", []).append(answer)
            evidence.setdefault("installCommands", []).append(answer)
        else:
            # Store as context keyed by the question
            short_key = question[:30]
            ctx[short_key] = answer

        # If the description is short, this might be clarifying it
        current_desc = project.get("description", "")
        if len(current_desc) < 40 and len(answer) > len(current_desc):
            project["description"] = answer
            evidence["opening"] = answer
            evidence["readmeOpening"] = answer

    # Build a combined context note for the AI
    if answers:
        qa_notes = "\n".join(f"Q: {q}\nA: {a}" for q, a in answers)
        ctx["interactiveQA"] = qa_notes

    return merged


# ---------------------------------------------------------------------------
# Utility
# ---------------------------------------------------------------------------

