"""Generate a launch-assets directory from source evidence and optional AI content."""
from __future__ import annotations

import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Any

DEFAULT_OUTPUT_DIR = "launch-assets"

# Maps AI JSON keys to human-readable file names
PLATFORM_FILES = {
    "xiaohongshu": "promo-xhs.md",
    "zhihu": "promo-zhihu.md",
    "wechatMoments": "promo-wechat.md",
    "showHn": "promo-show-hn.md",
    "productHunt": "promo-product-hunt.md",
    "twitter": "promo-twitter.md",
    "linkedin": "promo-linkedin.md",
    "reddit": "promo-reddit.md",
}

PLATFORM_LABELS = {
    "xiaohongshu": "小红书",
    "zhihu": "知乎",
    "wechatMoments": "微信",
    "showHn": "Show HN",
    "productHunt": "Product Hunt",
    "twitter": "Twitter / X",
    "linkedin": "LinkedIn",
    "reddit": "Reddit",
}


def run_optimize(
    result: dict[str, Any],
    *,
    cwd: str | Path | None = None,
    output_dir: str | Path | None = None,
    ai_content: dict[str, Any] | None = None,
    ai_model: str | None = None,
    generate_images: bool = False,
    image_options: dict[str, Any] | None = None,
) -> dict[str, Any]:
    root = Path(cwd or ".").resolve()
    out = Path(output_dir or DEFAULT_OUTPUT_DIR)
    if not out.is_absolute():
        out = root / out
    out.mkdir(parents=True, exist_ok=True)

    generated: list[str] = []
    images: list[dict[str, Any]] = []
    project = result.get("project", {})
    evidence = result.get("evidence", {})

    if generate_images:
        # Run text writing and image generation in parallel
        from .image import generate_platform_images

        def _write_text() -> None:
            _write_promo_files(out, project, evidence, ai_content, generated)

        def _write_images() -> list[dict[str, Any]]:
            return generate_platform_images(result, out, image_options)

        with ThreadPoolExecutor(max_workers=2) as executor:
            text_future  = executor.submit(_write_text)
            image_future = executor.submit(_write_images)

            # Collect results; propagate text errors, swallow image errors
            text_future.result()
            try:
                images = image_future.result()
            except Exception as exc:  # noqa: BLE001
                print(f"source2launch: image generation failed: {exc}", file=sys.stderr)
    else:
        _write_promo_files(out, project, evidence, ai_content, generated)

    # INDEX.md (after both futures complete)
    image_names = [Path(img["outputPath"]).name for img in images if img.get("outputPath")]
    write_file(out / "INDEX.md", _index(project, generated, ai_model, image_names), generated)

    return {
        "project": project.get("name"),
        "outputDir": str(out),
        "promoSource": "ai" if ai_content else "unavailable",
        "promoModel": ai_model,
        "generated": generated,
        "images": images,
    }


def _write_promo_files(
    out: Path,
    project: dict[str, Any],
    evidence: dict[str, Any],
    ai_content: dict[str, Any] | None,
    generated: list[str],
) -> None:
    """Write evidence summary and all platform promo files."""
    write_file(out / "evidence-summary.md", _evidence_summary(project, evidence), generated)
    promotions = (ai_content or {}).get("promotions", {})
    for key, filename in PLATFORM_FILES.items():
        item = promotions.get(key)
        content = _extract_markdown(item)
        write_file(out / filename, content if content else _placeholder(PLATFORM_LABELS[key], project), generated)


def write_file(path: Path, content: str, manifest: list[str]) -> None:
    path.write_text(content.rstrip() + "\n", encoding="utf-8")
    manifest.append(path.name)


def _extract_markdown(item: Any) -> str:
    if isinstance(item, str):
        return item.strip()
    if isinstance(item, dict):
        return str(item.get("markdown") or "").strip()
    return ""


def _evidence_summary(project: dict[str, Any], evidence: dict[str, Any]) -> str:
    lines = [
        f"# {project.get('name', 'Project')} · Evidence Summary",
        "",
        "> Auto-generated by Source2Launch. Review before using in promotional content.",
        "",
        "## Project",
        "",
    ]
    if project.get("description"):
        lines += [f"**Description:** {project['description']}", ""]
    if project.get("installCommand"):
        lines += [f"**Install:** `{project['installCommand']}`", ""]
    if project.get("repositoryUrl"):
        lines += [f"**Repository:** {project['repositoryUrl']}", ""]
    if project.get("stars") is not None:
        lines += [f"**Stars:** {project['stars']}", ""]
    if project.get("topics"):
        lines += [f"**Topics:** {', '.join(project['topics'])}", ""]

    opening = evidence.get("readmeOpening", "")
    if opening:
        lines += ["## README Opening", "", opening, ""]

    risks = evidence.get("launchRisks", [])
    if risks:
        lines += ["## Launch Risks", ""]
        for r in risks:
            msg = r.get("message") if isinstance(r, dict) else str(r)
            lines.append(f"- {msg}")
        lines.append("")

    return "\n".join(lines)


def _placeholder(label: str, project: dict[str, Any]) -> str:
    name = project.get("name", "Project")
    return "\n".join([
        f"# {name} · {label}",
        "",
        "> No AI content generated yet.",
        "> Run with `--ai` to generate platform copy.",
        "",
    ])


def _index(
    project: dict[str, Any],
    generated: list[str],
    model: str | None,
    image_names: list[str] | None = None,
) -> str:
    name = project.get("name", "Project")
    model_str = f" · model: {model}" if model else ""
    lines = [
        f"# {name} · Launch Assets",
        "",
        f"Generated by Source2Launch{model_str}",
        "",
        "## Files",
        "",
    ]
    for f in generated:
        if f != "INDEX.md":
            lines.append(f"- [{f}]({f})")
    if image_names:
        lines += ["", "## Images", ""]
        for img in image_names:
            lines.append(f"- [images/{img}](images/{img})")
    lines += [
        "",
        "## Review Before Publishing",
        "",
        "- Verify all facts against the original README, paper, or source.",
        "- Remove any claims not supported by source evidence.",
        "- Adapt tone and format to match your account voice.",
        "- Do not publish automatically — review each draft first.",
        "",
    ]
    return "\n".join(lines)
