"""Interactive setup wizard for PromoAgent first-time users."""
from __future__ import annotations

import os
from pathlib import Path
from typing import Any

from rich.console import Console
from rich.prompt import Prompt, Confirm
from rich.panel import Panel
from rich.table import Table
from rich import box

console = Console()


def run_setup() -> int:
    """Run the interactive setup wizard."""
    console.print(Panel(
        "[bold cyan]Welcome to PromoAgent Setup![/]\n\n"
        "This wizard will help you configure PromoAgent for the first time.",
        title="🚀 Getting Started",
        border_style="cyan",
        box=box.ROUNDED,
    ))

    env_vars = {}

    # Step 1: Choose provider
    console.print("\n[bold]Step 1: Choose your AI Provider[/]")
    providers = [
        ("ModelScope (Recommended - China)", "modelscope"),
        ("OpenAI", "openai"),
        ("Anthropic Claude", "anthropic"),
        ("Google Gemini", "gemini"),
        ("Ollama (Local)", "ollama"),
    ]

    for i, (name, _) in enumerate(providers, 1):
        console.print(f"  {i}. {name}")

    choice = Prompt.ask("Select provider", choices=["1", "2", "3", "4", "5"], default="1")
    provider = providers[int(choice) - 1][1]

    # Step 2: API Key
    console.print(f"\n[bold]Step 2: Configure {provider.title()}[/]")

    if provider == "modelscope":
        key = Prompt.ask("Enter your ModelScope API Key", password=True)
        if key:
            env_vars["PROMOAGENT_MODELSCOPE_API_KEY"] = key
            env_vars["PROMOAGENT_BASE_URL"] = "https://api-inference.modelscope.cn/v1"
            env_vars["PROMOAGENT_MODEL"] = "Qwen/Qwen3.5-397B-A17B"
    elif provider == "openai":
        key = Prompt.ask("Enter your OpenAI API Key", password=True)
        if key:
            env_vars["PROMOAGENT_API_KEY"] = key
            env_vars["PROMOAGENT_MODEL"] = "gpt-4o-mini"
    elif provider == "anthropic":
        key = Prompt.ask("Enter your Anthropic API Key", password=True)
        if key:
            env_vars["ANTHROPIC_API_KEY"] = key
            env_vars["PROMOAGENT_MODEL"] = "claude-haiku-4-5"
    elif provider == "gemini":
        key = Prompt.ask("Enter your Google API Key", password=True)
        if key:
            env_vars["GOOGLE_API_KEY"] = key
            env_vars["PROMOAGENT_MODEL"] = "gemini-2.0-flash"
    elif provider == "ollama":
        env_vars["OLLAMA_BASE_URL"] = "http://localhost:11434"
        env_vars["PROMOAGENT_MODEL"] = "llama3.2"
        console.print("[dim]Make sure Ollama is running: ollama serve && ollama pull llama3.2[/]")

    # Step 3: Optional features
    console.print("\n[bold]Step 3: Optional Features[/]")

    if Confirm.ask("Enable Tavily web search for better examples?", default=False):
        key = Prompt.ask("Enter Tavily API Key", password=True)
        if key:
            env_vars["TAVILY_API_KEY"] = key

    if Confirm.ask("Enable browser auto-fill? (requires Playwright)", default=False):
        console.print("[dim]Run: pip install 'promoagent[fill]'[/]")

    if Confirm.ask("Enable MCP Server? (for Claude Desktop integration)", default=False):
        console.print("[dim]Run: pip install 'promoagent[mcp]'[/]")

    # Step 4: Write .env file
    console.print("\n[bold]Step 4: Saving Configuration[/]")

    env_path = Path(".env")
    if env_path.exists():
        backup = Path(".env.backup")
        backup.write_text(env_path.read_text(), encoding="utf-8")
        console.print(f"[yellow]Backed up existing .env to .env.backup[/]")

    # Build env content
    lines = ["# PromoAgent Configuration", "# Generated by setup wizard", ""]

    for key, value in env_vars.items():
        lines.append(f"{key}={value}")

    lines.extend([
        "",
        "# Optional: Adjust these as needed",
        "PROMOAGENT_MAX_TOKENS=4096",
        "PROMOAGENT_TEMPERATURE=0.7",
    ])

    env_path.write_text("\n".join(lines), encoding="utf-8")

    console.print(Panel(
        "[bold green]✓ Setup complete![/]\n\n"
        f"Configuration saved to [cyan].env[/]\n\n"
        "Next steps:\n"
        "  1. Run [cyan]promoagent doctor[/] to verify setup\n"
        "  2. Run [cyan]promoagent analyze .[/] to test\n"
        "  3. Run [cyan]promoagent promote . --ai[/] to generate content",
        title="🎉 All Done",
        border_style="green",
        box=box.ROUNDED,
    ))

    return 0


def run_doctor() -> int:
    """Check configuration and dependencies."""
    from .ai import has_ai_key
    from .cache import get_stats
    from .image import has_image_key

    console.print(Panel(
        "[bold cyan]PromoAgent Configuration Check[/]",
        border_style="cyan",
        box=box.ROUNDED,
    ))

    table = Table(show_header=False, box=box.SIMPLE)
    table.add_column("Check", style="bold")
    table.add_column("Status")
    table.add_column("Details", style="dim")

    # Check Python version
    import sys
    py_version = f"{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}"
    if sys.version_info >= (3, 10):
        table.add_row("Python Version", "[green]✓[/]", f"{py_version} (OK)")
    else:
        table.add_row("Python Version", "[red]✗[/]", f"{py_version} (Need 3.10+)")

    ai_ok = has_ai_key()
    image_ok = has_image_key()

    # Check AI API Key
    if ai_ok:
        table.add_row("AI API Key", "[green]✓[/]", "Configured")
    else:
        table.add_row("AI API Key", "[red]✗[/]", "Not found (run: promoagent setup)")

    # Check Image API Key
    if image_ok:
        table.add_row("Image API Key", "[green]✓[/]", "Configured")
    else:
        table.add_row("Image API Key", "[dim]○[/]", "Not found (set PROMOAGENT_IMAGE_API_KEY)")

    # Check optional dependencies
    optional_deps = [
        ("pypdf", "PDF text extraction", "pdf"),
        ("pypdfium2", "PDF rendering", "ocr"),
        ("pytesseract", "OCR for scanned PDFs", "ocr"),
        ("gradio", "Web UI", "web"),
        ("playwright", "Browser auto-fill", "fill"),
        ("mcp", "MCP Server", "mcp"),
    ]

    for module, name, extra in optional_deps:
        try:
            __import__(module)
            table.add_row(name, "[green]✓[/]", f"Installed ({extra})")
        except ImportError:
            table.add_row(name, "[dim]○[/]", f"Not installed (pip install 'promoagent\\[{extra}]')")

    # Check cache
    stats = get_stats()
    table.add_row("Cache", "[green]✓[/]", f"{stats['entries']} entries, {stats['size_human']}")

    console.print(table)

    # Overall status
    if ai_ok or image_ok:
        console.print(Panel(
            "[bold green]✓ PromoAgent has usable API configuration for the enabled feature set.[/]",
            border_style="green",
            box=box.ROUNDED,
        ))
        return 0
    else:
        console.print(Panel(
            "[bold yellow]⚠ Configuration incomplete[/]\n\n"
            "Please run [cyan]promoagent setup[/] to configure your API keys.",
            border_style="yellow",
            box=box.ROUNDED,
        ))
        return 1
